---
# vars file for SoapyRTLSDR

pkg_name: soapyrtlsdr
version: '0.3.3'
git_commit: '80c93fbe189'
name_version: '{{ pkg_name }}-{{ version }}'
mirror: https://github.com/pothosware/SoapyRTLSDR.git
pkg_build_dir: '{{ build_dir }}/{{ pkg_name }}-{{ version }}'
#stow_path: '{{ stow_dir }}/{{ name_version }}'
cmake_defines: ''
required_system_packages:
  - rtl-sdr
  - librtlsdr-dev
enabled: yes