---
# vars file for flrig

this_name: flrig
this_version: 1.4.7
this_source_uri: 'http://www.w1hkj.com/files/flrig/flrig-{{ this_version }}.tar.gz'

name_version: '{{ this_name }}-{{ this_version }}'
this_required_system_packages:
  - build-essential
  - libfltk1.3-dev
  - libudev-dev
this_conflicting_system_packages:
  - flrig