- block:

  - stat:
      path: '{{ hamclock_stow_path }}/bin/{{ target }}'
    register: result

  - name: 'Build {{ target }}'
    community.general.make:
      chdir: '{{ download_dir }}//ESPHamClock'
      target: '{{ target }}'
      jobs: 4
    when: not result.stat.exists
  
  - name: 'Copy {{ target }}'
    copy:
      src: '{{ download_dir }}//ESPHamClock/{{ target }}'
      dest: '{{ hamclock_stow_path }}/bin/'
      mode: preserve
      remote_src: yes
    when: not result.stat.exists
    become: true

  - name: Create .desktop file
    template:
      src: desktop.j2
      dest: '{{ hamclock_stow_path }}/share/applications/{{ target }}.desktop'
    when: not result.stat.exists
    become: true
