---
# tasks file for hamclock

- name: Install system packages for {{ name_version }}
  package:
    name: '{{ required_system_packages }}'
    state: latest
  become: true
  tags: 'prepare'

- include_role: 
    name: get_source
  vars:
    method: 'download_archive'
    pkg_name: '{{ name_version }}'
    source_uri: 'http://www.clearskyinstitute.com/ham/HamClock/ESPHamClock.tgz'
    destination: '{{ download_dir }}/{{ name_version }}'
  tags: 'get_source'

- name: Copy print_version.c
  copy:
    content: |
      #include <stdio.h>
      #include "version.h"

      int main() {
        puts(HC_VERSION);
      }
    dest: '{{ download_dir }}/ESPHamClock/print_version.c'

- name: Build print_version
  shell:
    cmd: gcc -o print_version print_version.c
    chdir: '{{ download_dir }}//ESPHamClock'
    creates: print_version

- name: Get version of hamclock
  command: 
    cmd: ./print_version
    chdir: '{{ download_dir }}//ESPHamClock'
  register: print_version

- name: Store version
  set_fact:
    hamclock_version: '{{ print_version.stdout }}'

- name: Store name_version
  set_fact:
    hamclock_name_version: '{{ this_name }}-{{ hamclock_version }}'
  
- name: Store stow_path
  set_fact:
    hamclock_stow_path: '{{ stow_dir }}/{{ hamclock_name_version }}'

- name: Create install directory
  become: true
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ hamclock_stow_path }}/{{ directory }}'
  loop: ['bin', 'share/applications', 'share/pixmaps']
  loop_control:
    loop_var: directory

- name: Copy icon
  copy:
    src: '{{ download_dir }}/ESPHamClock/hamclock.png'
    dest: '{{ hamclock_stow_path }}/share/pixmaps/'
    remote_src: yes
  become: true

- name: Build and install
  include_tasks: build_copy.yml
  loop: '{{ hamclock_executables }}'
  loop_control:
    loop_var: target

- name: Stow {{ name_version }}
  command:
    cmd: 'stow -R {{ hamclock_name_version }}'
    chdir: '{{ stow_dir }}'
  become: true
