---
# vars file for qsstv

this_name: qsstv
this_version: 9.5.8
#this_source_uri: 'http://users.telenet.be/on4qz/qsstv/downloads/qsstv_{{ this_version }}.tar.gz'
this_source_uri: 'https://web.archive.org/web/20220831224529if_/http://users.telenet.be/on4qz/qsstv/downloads/qsstv_{{ this_version }}.tar.gz'

name_version: '{{ this_name }}-{{ this_version }}'
this_required_system_packages:
  - g++
  - libfftw3-dev
  - qtbase5-dev
  - libasound2-dev
  - libpulse-dev
  - libopenjp2-7
  - libopenjp2-7-dev
  - libv4l-dev
