---
# tasks file for wxwidgets

- include_role: 
    name: standard_package
  vars:
    pkg_basename: '{{ this_name }}'
    pkg_version: '{{ this_version }}'
    get_method: 'git'
    build_method: 'configure'
    required_system_packages: '{{ this_required_system_packages }}'
    conflicting_system_packages: '{{ this_conflicting_system_packages }}'
    source_uri: '{{ this_source_uri }}'
    destination: '{{ download_dir }}/{{ name_version }}'
    version: 'v{{ this_version }}'
    source_path: '{{ download_dir }}/{{ name_version }}'
    build_path: '{{ build_dir }}/{{ name_version }}'
    install_path: '{{ stow_dir }}/{{ name_version }}'
    bootstrap_command: './autogen.sh'
    bootstrapped: '{{ download_dir }}/{{ name_version }}/configure'
    configure_options: '--with-gtk=3'
    ldconfig: true
