---
# tasks file for wxwidgets

- name: Install system packages for {{ name_version }}
  package:
    name: '{{ required_system_packages }}'
    state: latest
  become: true
  tags: 'prepare'

- include_role: 
    name: get_source
  vars:
    method: 'git'
    pkg_name: '{{ name_version }}'
    source_uri: 'https://github.com/wxWidgets/wxWidgets'
    destination: '{{ download_dir }}/{{ name_version }}'
    commit: 'v{{ this_version }}'
  tags: 'get_source'

- name: Remove conflicting system packages for {{ name_version }}
  package:
    name:
    - wx-common
    state: absent
  become: true
  tags: 'cleanup'

- name: Create build directory for {{ name_version }}
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ build_dir }}/{{ name_version }}'

- name: Create ./configure for {{ name_version }}
  command:
    cmd: './autogen.sh'
    chdir: '{{ download_dir }}/{{ name_version }}'
  args:
    creates: '{{ download_dir }}/{{ name_version }}/configure'
  tags: 'build'

- include_role: 
    name: build_install
  vars:
    method: 'configure'
    pkg_name: '{{ name_version }}'
    source_path: '{{ download_dir }}/{{ name_version }}'
    build_path: '{{ build_dir }}/{{ name_version }}'
    install_path: '{{ stow_dir }}/{{ name_version }}'
    configure_options: '--with-gtk=3'

- name: Stow {{ name_version }}
  command:
    cmd: 'stow -R {{ name_version }}'
    chdir: '{{ stow_dir }}'
  become: true

- name: Update systems shared libraries
  command:
    cmd: ldconfig
  become: true
