---
# tasks file for codecserver

- include_role: 
    name: standard_package
  vars:
    pkg_name: '{{ name_version }}'
    get_method: 'git'
    build_method: 'cmake'
    required_system_packages: '{{ this_required_system_packages }}'
    conflicting_system_packages: '{{ this_conflicting_system_packages }}'
    source_uri: '{{ this_repository }}'
    destination: '{{ download_dir }}/{{ name_version }}'
    version: '{{ this_version }}'
    source_path: '{{ download_dir }}/{{ name_version }}'
    build_path: '{{ build_dir }}/{{ name_version }}'
    install_path: '{{ stow_dir }}/{{ name_version }}'
    cmake_defines: '{{ this_cmake_defines }}'
    ldconfig: false

- name: Create user for {{ pkg_name }}
  user:
    name: '{{ codecserver_user }}'
    state: present
    system: yes
    groups: dialout
  become: true