---
# tasks file for hamlib

- include_tasks: tasks/check_installed.yml

- block:

  - include_tasks: tasks/git_versioned.yml

  - include_tasks: tasks/install_required_system_packages.yml

  # Remove Debian version of hamlib?
  # is there a conflict?

  - name: Create ./configure for {{ name_version }}
    command:
      cmd: ./bootstrap
      chdir: '{{ pkg_build_dir }}'
    args:
      creates: '{{ pkg_build_dir }}/configure'

  - include_tasks: tasks/configure_make_install.yml

  - include_tasks: tasks/unstow.yml

  - include_tasks: tasks/stow.yml

  - name: Update systems shared libraries
    command:
      cmd: ldconfig
    become: yes

  - include_tasks: ../../../tasks/mark_as_installed.yml 

  when: not installed.stat.exists