---
# vars file for SoapySDR

this_name: soapysdr
this_version: '0.8.1'
git_commit: '1cf5a539'
name_version: '{{ this_name }}-{{ this_version }}'
soapysdr_name_version: '{{ name_version }}'
required_system_packages:
  - build-essential
  - cmake
  - g++
  - libpython3-dev
  - python2-dbg
  - python3-numpy
  - swig
