---
# vars file for SoapySDR

this_name: soapysdr
this_version: '0.8.1'
this_source_uri: 'https://github.com/pothosware/SoapySDR.git'

name_version: '{{ this_name }}-{{ this_version }}'
soapysdr_name_version: '{{ name_version }}'
this_required_system_packages:
  - build-essential
  - cmake
  - g++
  - libpython3-dev
  - python2-dbg
  - python3-numpy
  - swig
this_conflicting_system_packages:
  - 'soapy*'
