---
# argument_specs file for build_install

argument_specs:
  # roles/myapp/tasks/main.yml entry point
  main:
    short_description: 'Configure build, build it and install the package.'
    options:
      method:
        description: 'Method for creating the Makefile'
        type: 'str'
        choices: ['cmake', 'qmake', 'configure']
        required: true

      pkg_basename:
        description: 'Name of the package without any version. Should be the same as the package roles name.'
        type: 'str'
        required: true

      pkg_version:
        description: 'Only the version of the package.'
        type: 'str'
        required: true

      source_path:
        description: 'Path to the sources.'
        type: 'path'
        required: true

      build_path:
        description: 'Path to the build directory for this package. The directory will be created, if not existing.'
        type: 'path'
        required: true

      install_path:
        description: 'Path to the directory, where the package is installed.'
        type: 'path'
        required: true

      qmake_profile:
        description: 'Path to the qmake profile file.'
        type: 'path'
        default: ''

      qmake_defines:
        description: 'Defines passed to qmake.'
        type: 'str'
        default: ''

      cmake_defines:
        description: 'Defines passed to cmake.'
        type: 'str'
        default: ''

      configure_options:
        description: 'Options passed to configure.'
        type: 'str'
        default: ''

      bootstrap_command:
        description: 'Command to run before configuring the build. E.g. autoconf.'
        type: 'path'

      bootstrapped:
        description: 'Path to file created by bootstrap_command.'
        type: 'path'

      install_options:
        description: 'Options passed to install command.'
        type: 'str'
        default: ''

