---
# tasks file for volk

- include_tasks: tasks/check_installed.yml

- block:

  - include_tasks: tasks/git_versioned.yml

  - include_tasks: tasks/install_required_system_packages.yml

  - name: Create build directory for {{ name_version }}
    file:
      state: directory
      mode: 'u=rwx,go=rx'
      dest: '{{ build_dir }}/{{ name_version }}-build'

  # - name: Create Makefile for {{ name_version }}
  #   command:
  #     cmd: cmake -DCMAKE_TOOLCHAIN_FILE='{{ pkg_build_dir }}/cmake/Toolchains/arm_cortex_a72_hardfp_native.cmake' -D CMAKE_INSTALL_PREFIX='{{ stow_path }}' {{ pkg_build_dir }}
  #     chdir: '{{ build_dir }}/{{ name_version }}-build'
  #     creates: Makefile

  - name: Create Makefile for {{ name_version }}
    command:
      cmd: cmake -D CMAKE_INSTALL_PREFIX='{{ stow_path }}' {{ pkg_build_dir }}
      chdir: '{{ build_dir }}/{{ name_version }}-build'
      creates: Makefile

  - name: Build {{ name_version }}
    make:
      jobs: 4
      chdir: '{{ build_dir }}/{{ name_version }}-build'

  - name: Test {{ name_version }}
    make:
      target: test
      chdir: '{{ build_dir }}/{{ name_version }}-build'

  - name: Install {{ name_version }}
    make:
      target: install
      chdir: '{{ build_dir }}/{{ name_version }}-build'
    notify: 'Update systems shared libraries'
    become: yes

  - include_tasks: tasks/stow.yml

  - include_tasks: tasks/mark_as_installed.yml 

  when: not installed.stat.exists