---
# tasks file for build_install

- name: Include tasks to build and install a python package
  include_tasks: python.yml
  when: method == 'python_setup'
  
- name: Include tasks to build and install a python package
  include_tasks: standard.yml
  when: method != 'python_setup'
