---
# vars file for uhd

pkg_name: uhd
version: 'v4.2.0.0'
name_version: '{{ pkg_name }}-{{ version }}'
mirror: https://github.com/EttusResearch/uhd.git
#archive: '{{ pkg_name }}_{{ version }}.tar.gz'
pkg_build_dir: '{{ build_dir }}/{{ pkg_name }}-{{ version }}'
stow_path: '{{ stow_dir }}/{{ name_version }}'
required_system_packages:
  - cmake
  - g++
  - libboost-all-dev
  - libgmp-dev
  - swig
  - python3-numpy
  - python3-mako
  - python3-sphinx
  - python3-lxml
  - doxygen
  - libfftw3-dev
  - libsdl1.2-dev
  - libgsl-dev
  - libqwt-qt5-dev
  - libqt5opengl5-dev
  - python3-pyqt5
  - liblog4cpp5-dev
  - libzmq3-dev
  - python3-yaml
  - python3-click
  - python3-click-plugins
  - python3-zmq
  - python3-scipy
  - libpthread-stubs0-dev
  - libusb-1.0-0
  - libusb-1.0-0-dev
  - libudev-dev
  - python3-setuptools
  - build-essential
  - liborc-0.4-0
  - liborc-0.4-dev
  - python3-gi-cairo
  - python3-docutils
  - python3-pip
cmake_defines: '-DNEON_SIMD_ENABLE=OFF'
enabled: yes