---
# tasks file for golang

- name: Download archives {{ name_version }}
  get_url:
    url: 'https://golang.org/dl/go{{ this_version }}.linux-{{ golang_architecture }}.tar.gz'
    dest: '{{ download_dir }}/go{{ this_version }}.linux-{{ golang_architecture }}.tar.gz'
    force: no
    use_proxy: yes
    validate_certs: yes
    mode: 'u=rw,go=r'

- name: Extract '{{ name_version }}'
  unarchive:
    src: '{{ download_dir }}//go{{ this_version }}.linux-{{ golang_architecture }}.tar.gz'
    remote_src: yes
    dest: '{{ install_dir }}'
    creates: '{{ install_dir }}/go'
  become: true

- name: Copy profile
  copy:
    content: |
      #!/bin/sh

      export GOROOT='{{ install_dir }}/go'
      export PATH=$PATH:$GOROOT/bin
    dest: '/etc/profile.d/golang.sh'
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
  register: result
  become: yes

- name: Reboot to source new profile
  reboot:
  when: result.changed
  become: yes
  