---
# tasks file for golang

- include_tasks: tasks/check_installed.yml

- block:
  - name: Download archives {{ name_version }}
    get_url:
      url: '{{ mirror }}/{{ archive }}'
      dest: '{{ download_dir }}/{{ archive }}'
      force: no
      use_proxy: yes
      validate_certs: yes
      mode: 'u=rw,go=r'

  - name: Extract '{{ name_version }}'
    unarchive:
      src: '{{ download_dir }}/{{ archive }}'
      remote_src: yes
      dest: '{{ install_dir }}'
      creates: '{{ install_dir }}/go'
    become: yes

  - name: Copy profile
    copy:
      content: |
        #!/bin/sh

        export GOROOT='{{ install_dir }}/go'
        export PATH=$PATH:$GOROOT/bin
      dest: '/etc/profile.d/golang.sh'
      owner: root
      group: root
      mode: 'u=rwx,go=rx'
    register: result
    become: yes

  - include_tasks: tasks/mark_as_installed.yml

  - name: Reboot to source new profile
    reboot:
    when: result.changed
    become: yes
  
  when: not installed.stat.exists