---
# tasks file for hamlib

- name: Install system packages for {{ name_version }}
  package:
    name: '{{ required_system_packages }}'
    state: latest
  become: true
  tags: 'prepare'

- include_role: 
    name: get_source
  vars:
    method: 'git'
    pkg_name: '{{ name_version }}'
    source_uri: 'https://github.com/Hamlib/Hamlib.git'
    destination: '{{ download_dir }}/{{ name_version }}'
    version: '{{ version }}'
  tags: 'get_source'

- name: Remove conflicting system packages for {{ name_version }}
  package:
    name:
    - libhamlib-dev
    state: absent
  become: true
  tags: 'cleanup'

- include_role: 
    name: build_install
  vars:
    method: 'configure'
    pkg_name: '{{ name_version }}'
    source_path: '{{ download_dir }}/{{ name_version }}'
    build_path: '{{ build_dir }}/{{ name_version }}'
    install_path: '{{ stow_dir }}/{{ name_version }}'
    configure_options: '--with-xml-support --with-readline --with-python-binding --with-tcl-binding --with-lua-binding'
    bootstrap_command: './bootstrap'
    bootstrapped: '{{ download_dir }}/{{ name_version }}/configure'

- name: Stow {{ name_version }}
  command:
    cmd: 'stow -R {{ name_version }}'
    chdir: '{{ stow_dir }}'
  become: true

- name: Update systems shared libraries
  command:
    cmd: ldconfig
  become: true
