---
# tasks file for qsstv

- name: Install {{ this_name }}-{{ this_version }}
  include_tasks: install.yml
  when: ansible_local[this_name] is not defined or ansible_local[this_name]['pkg_version'] != this_version


