---
dependencies:
  - role: packages/aptdec
    tags: aptdec

  - role: packages/cm256cc
    tags: cm256cc

  - role: packages/libdab
    tags: libdab

  - role: packages/mbelib
    tags: mbelib

  - role: packages/serialdv
    tags: serialdv

  - role: packages/dsdcc
    tags: dsdcc

  - role: packages/freedv
    tags: freedv

  - role: packages/sgp4
    tags: sgp4

  - role: packages/libsigmf
    tags: libsigmf

