---
# vars file for hamclock

this_name: hamclock
version: dynamic
name_version: '{{ this_name }}-{{ this_version }}'
pkg_build_dir: '{{ build_dir }}/ESPHamClock'
required_system_packages:
  - g++
  - libx11-dev
