---
# vars file for wfview

pkg_name: wfview
version: 'test'
name_version: '{{ pkg_name }}-{{ version }}'
mirror: https://gitlab.com/dersuessmann/wfview.git
#archive: '{{ name_version }}.tar.gz'
pkg_build_dir: '{{ build_dir }}/{{ pkg_name }}-{{ version }}'
stow_path: '{{ stow_dir }}/{{ name_version }}'
required_system_packages:
  - build-essential
  - qt5-qmake
  - qt5-default
  - libqt5core5a
  - qtbase5-dev
  - libqt5serialport5
  - libqt5serialport5-dev
  - libqt5multimedia5
  - libqt5multimedia5-plugins
  - qtmultimedia5-dev
  - libqcustomplot2.0
  - libqcustomplot-doc
  - libqcustomplot-dev
enabled: yes