---
# vars file for wfview

pkg_name: wfview
version: '1.2e'
name_version: '{{ pkg_name }}-{{ version }}'
mirror: https://gitlab.com/eliggett/wfview.git
pkg_build_dir: '{{ build_dir }}/{{ pkg_name }}-{{ version }}'
stow_path: '{{ stow_dir }}/{{ name_version }}'
required_system_packages:
  - build-essential
  - qt5-qmake
  - qtbase5-dev
  - libqt5core5a
  - qtbase5-dev
  - libqt5serialport5
  - libqt5serialport5-dev
  - libqt5multimedia5
  - libqt5multimedia5-plugins
  - qtmultimedia5-dev
  - libqcustomplot2.0
  - libqcustomplot-doc
  - libqcustomplot-dev
  - libopus-dev
enabled: yes