---

- name: Create build directory for {{ name_version }}
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ build_dir }}/{{ name_version }}/build'

- name: Create Makefile for {{ name_version }}
  command:
    cmd: cmake '{{ cmake_defines }}' -D CMAKE_INSTALL_PREFIX='{{ stow_path }}' {{ pkg_build_dir }}
    chdir: '{{ build_dir }}/{{ name_version }}/build'
    creates: Makefile
  when: cmake_defines is defined and cmake_defines != ''

- name: Create Makefile for {{ name_version }}
  command:
    cmd: cmake -D CMAKE_INSTALL_PREFIX='{{ stow_path }}' {{ pkg_build_dir }}
    chdir: '{{ build_dir }}/{{ name_version }}/build'
    creates: Makefile
  when: cmake_defines is not defined or cmake_defines == ''

- name: Create Makefile for {{ name_version }}
  command:
    cmd: cmake {{ pkg_build_dir }}
    chdir: '{{ build_dir }}/{{ name_version }}/build'
    creates: Makefile
  when: cmake_defines is not defined or cmake_defines == ''

- name: Build {{ name_version }}
  make:
    chdir: '{{ build_dir }}/{{ name_version }}/build'
    params:
      PREFIX: '{{ stow_path }}'
    jobs: '{{ make_jobs_number }}'        

- name: Install {{ name_version }}
  make:
    chdir: '{{ build_dir }}/{{ name_version }}/build'
    target: install
    params:
      PREFIX: '{{ stow_path }}'
  become: yes

