---

- name: Create Makefile for {{ name_version }}
  command:
    cmd: './configure --prefix={{ stow_path }} {{ configure_options | default("") }}'
    chdir: '{{ pkg_build_dir  }}'
    creates: '{{ pkg_build_dir }}/Makefile'

- name: Build {{ name_version }}
  make:
    chdir: '{{ pkg_build_dir }}'
    params:
      PREFIX: '{{ stow_path }}'
    jobs: '{{ make_jobs_number }}'        

- name: Install {{ name_version }}
  make:
    chdir: '{{ pkg_build_dir }}'
    target: install
    params:
      PREFIX: '{{ stow_path }}'
  become: yes
