---

- name: Create download directory
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ download_dir }}'

- block:

  - name: Download archives {{ name_version }}
    get_url:
      url: '{{ mirror }}/{{ archive }}'
      dest: '{{ download_dir }}/{{ archive }}'
      force: no
      use_proxy: yes
      validate_certs: yes
      mode: 'u=rw,go=r'

  - name: Unarchive {{ name_version }}
    unarchive:
      src: '{{ download_dir }}/{{ archive }}'
      remote_src: yes
      dest: '{{ build_dir }}'
      creates: '{{ pkg_build_dir }}'

  when: enabled is defined and enabled and archive is defined
