---
# tasks file for soapyrtlsdr

- include_role: 
    name: standard_package
  vars:
    pkg_basename: '{{ this_name }}'
    pkg_version: '{{ this_version }}'
    get_method: 'git'
    build_method: 'cmake'
    required_system_packages: '{{ this_required_system_packages }}'
    conflicting_system_packages: '{{ this_conflicting_system_packages }}'
    source_uri: '{{ this_source_uri }}'
    destination: '{{ download_dir }}/{{ name_version }}'
    version: ' soapy-rtl-sdr-{{ this_version }}'
    source_path: '{{ download_dir }}/{{ name_version }}'
    build_path: '{{ build_dir }}/{{ name_version }}'
    install_path: '{{ stow_dir }}/{{ name_version }}'
    ldconfig: true
