---
# tasks file for flrig

- name: Install system packages for {{ name_version }}
  package:
    name: '{{ required_system_packages }}'
    state: latest
  become: true
  tags: 'prepare'

- include_role:
    name: get_source
  vars:
    method: 'download_archive'
    pkg_name: '{{ name_version }}'
    source_uri: 'http://www.w1hkj.com/files/flrig/flrig-{{ this_version }}.tar.gz'
    destination: '{{ download_dir }}/{{ name_version }}'
  tags: 'get_source'

- name: Remove conflicting system packages for {{ name_version }}
  package:
    name:
    - flrig
    state: absent
  become: true
  tags: 'cleanup'

- include_role: 
    name: build_install
  vars:
    method: 'configure'
    pkg_name: '{{ name_version }}'
    source_path: '{{ download_dir }}/{{ name_version }}'
    build_path: '{{ build_dir }}/{{ name_version }}'
    install_path: '{{ stow_dir }}/{{ name_version }}'
    bootstrap_command: 'autoreconf -i'
    bootstrapped: '{{ download_dir }}/{{ name_version }}/configure'
  tags: 'build'

- name: Stow {{ name_version }}
  command:
    cmd: 'stow -R {{ name_version }}'
    chdir: '{{ stow_dir }}'
  become: true
