---
# tasks file for uhd

- name: Install system packages for {{ name_version }}
  package:
    name: '{{ required_system_packages }}'
    state: latest
  become: true
  tags: 'prepare'

- include_role: 
    name: get_source
  vars:
    method: 'git'
    pkg_name: '{{ name_version }}'
    source_uri: 'https://github.com/EttusResearch/uhd.git'
    destination: '{{ download_dir }}/{{ name_version }}'
    commit: 'v{{ this_version }}'
  tags: 'get_source'

- name: Remove conflicting system packages for {{ name_version }}
  package:
    name:
    - 'uhd*'
    state: absent
  become: true
  tags: 'cleanup'

- include_role: 
    name: build_install
  vars:
    method: 'cmake'
    pkg_name: '{{ name_version }}'
    source_path: '{{ download_dir }}/{{ name_version }}'
    build_path: '{{ build_dir }}/{{ name_version }}'
    install_path: '{{ stow_dir }}/{{ name_version }}'
    cmake_defines: "-DCMAKE_SHARED_LINKER_FLAGS='-latomic' '-DNEON_SIMD_ENABLE=OFF'"

- name: Stow {{ name_version }}
  command:
    cmd: 'stow -R {{ name_version }}'
    chdir: '{{ stow_dir }}'
  become: true

- name: Copy udev.rules
  copy:
    src: '{{ build_dir }}/{{ name_version }}/host/utils/uhd-usrp.rules'
    dest: '{{ stow_dir }}/etc/udev/rules.d/'
    remote_src: yes
  notify: 'Reload udev rules'

- name: Update systems shared libraries
  command:
    cmd: ldconfig
  notify: 'Download the UHD FPGA Images for this installation'
  become: true
