---
# tasks file for standard_package

- name: Install {{ pkg_basename }}-{{ pkg_version }}
  include_tasks: install.yml
  when: ansible_local[pkg_basename] is not defined or ansible_local[pkg_basename]['pkg_version'] != pkg_version


