---
# vars file for cubicsdr

this_name: cubicsdr
this_version: '0.2.7'
name_version: '{{ this_name }}-{{ this_version }}'
required_system_packages:
  - build-essential
  - cmake
  - libpulse-dev
  - libgtk-3-dev
  - freeglut3
  - freeglut3-dev
