---
# vars file for qsstv

pkg_name: qsstv
version: 9.5.8
name_version: '{{ pkg_name }}-{{ version }}'
mirror: http://users.telenet.be/on4qz/qsstv/downloads/
archive: 'qsstv_{{ version }}.tar.gz'
pkg_build_dir: '{{ build_dir }}/qsstv_{{ version }}'
stow_path: '{{ stow_dir }}/{{ name_version }}'
required_system_packages:
  - g++
  - libfftw3-dev
  - qt5-default
  - libasound2-dev
  - libpulse-dev
  - libopenjp2-7
  - libopenjp2-7-dev
  - libv4l-dev
enabled: yes
