- name: Install all packages
  hosts: ham

  vars_files:
  - vars/main.yml

  tasks:

  - name: Create download directory
    file:
      state: directory
      mode: 'u=rwx,go=rx'
      dest: '{{ download_dir }}'
    tags: prepare
  
  - name: Create build directory
    file:
      state: directory
      mode: 'u=rwx,go=rx'
      dest: '{{ build_dir }}'
    tags: prepare

  - name: Create directory for ansible custom facts
    file:
      state: directory
      recurse: yes
      path: /etc/ansible/facts.d
    become: true

- import_playbook: upgrade_system.yml
- import_playbook: setup.yml

- import_playbook: install.yml

