---

- hosts: all

  vars_files:
    - vars/main.yml

  tasks:

    - include_role:
        name: qsstv

    - include_role: 
        name: kappanhang

    - include_role: 
        name: wfview

    - include_role:
        name: hamclock
