---

- hosts: all

  vars_files:
    - vars/main.yml

  roles:
    - role: swapfile
      vars:
        swapfile_state: present
      become: yes
      tags: prepare

    - role: packages/sdrangel
      tags: sdrangel

    - role: packages/gqrx
      tags: gqrx

    # - role: gpredict
    #   tags: gpredict

    - role: packages/fldigi
      tags: 
        - fldigi
        - fltools
        
    - role: packages/flrig
      tags: 
        - flrig
        - fltools
        
    - role: packages/fllog
      tags: 
        - fllog
        - fltools
        
    - role: packages/wsjtx
      tags: wsjtx

    - role: packages/qsstv
      tags: qsstv
        
    - role: packages/wfview
      tags: wfview

    - role: packages/soapysdr
      tags: soapysdr

    - role: packages/cubicsdr
      tags: cubicsdr



    # hamclock role is broken and must be called last  
    - role: packages/hamclock
      hamclock_executables: 
        - 'hamclock'
        #- 'hamclock-big'
        - 'hamclock-2400x1440'
        - 'hamclock-3200x1920'
      tags: hamclock
        
    - role: packages/kappanhang
      tags: kappanhang
