---

- hosts: all

  vars_files:
    - vars/main.yml

  tasks:

    - include_role:
        name: gpredict

    - include_role:
        name: fldigi
        
    - include_role:
        name: flrig

    - include_role:
        name: fllog

    - include_role:
        name: wsjtx

    - include_role:
        name: qsstv

    - include_role: 
        name: kappanhang

    - include_role: 
        name: wfview

    - include_role:
        name: gqrx

    - include_role:
        name: cubicsdr

    # hamclock role is broken and must be called last
    - include_role:
        name: hamclock
