---

- hosts: all

  vars_files:
    - vars/main.yml

  roles:
    - role: swapfile
      vars:
        swapfile_state: present
      become: yes
      tags: prepare

    - role: gnuradio
      tags: gnuradio

    - role: gqrx
      tags: gqrx

    - role: gpredict
      tags: gpredict

    - role: fldigi
      tags: 
        - fldigi
        - fltools
        
    - role: flrig
      tags: 
        - flrig
        - fltools
        
    - role: fllog
      tags: 
        - fllog
        - fltools
        
    - role: wsjtx
      tags: wsjtx

    - role: qsstv
      tags: qsstv
        
    - role: kappanhang
      tags: kappanhang
        
    - role: wfview
      tags: wfview

    - role: soapysdr
      tags: soapysdr

    - role: cubicsdr
      tags: cubicsdr



    # hamclock role is broken and must be called last  
    - role: hamclock
      hamclock_executables: 
        - 'hamclock'
        #- 'hamclock-big'
        - 'hamclock-2400x1440'
        - 'hamclock-3200x1920'
      tags: hamclock
        
