- name: Upgrade system
  hosts: all

  tasks:

  - name: Update all packages to the latest version
    become: yes
    apt:
      update_cache: yes
      upgrade: dist
    tags: prepare

  - name: Autoremove unneeded packages
    become: yes
    apt:
      autoremove: yes
    tags: prepare

  - name: Remove unneeded packages from the cache
    become: yes
    apt:
      autoclean: yes
    tags: prepare