---
# tasks file for soapyrtlsdr

- name: Install system packages for {{ name_version }}
  package:
    name: '{{ required_system_packages }}'
    state: latest
  become: true
  tags: 'prepare'

- include_role: 
    name: get_source
  vars:
    method: 'git'
    pkg_name: '{{ name_version }}'
    source_uri: 'https://github.com/pothosware/SoapyPlutoSDR.git'
    destination: '{{ download_dir }}/{{ name_version }}'
    commit: 'a2431282fc2'
  tags: 'get_source'

- name: Remove conflicting system packages for {{ name_version }}
  package:
    name:
    - 'soapy*'
    state: absent
  become: true
  tags: 'cleanup'

- include_role: 
    name: build_install
  vars:
    method: 'cmake'
    pkg_name: '{{ name_version }}'
    source_path: '{{ download_dir }}/{{ name_version }}'
    build_path: '{{ build_dir }}/{{ name_version }}'
    install_path: '{{ stow_dir }}/{{ soapysdr_name_version }}'

- name: Stow {{ name_version }}
  command:
    cmd: 'stow -R {{ soapysdr_name_version }}'
    chdir: '{{ stow_dir }}'
  become: true

- name: Update systems shared libraries
  command:
    cmd: ldconfig
  become: true
