---
# vars file for wfview

this_name: wfview
this_version: '1.2e'
this_source_uri: 'https://gitlab.com/eliggett/wfview.git'

name_version: '{{ this_name }}-{{ this_version }}'
this_required_system_packages:
  - build-essential
  - qt5-qmake
  - qtbase5-dev
  - libqt5core5a
  - qtbase5-dev
  - libqt5serialport5
  - libqt5serialport5-dev
  - libqt5multimedia5
  - libqt5multimedia5-plugins
  - qtmultimedia5-dev
  - libqcustomplot2.0
  - libqcustomplot-doc
  - libqcustomplot-dev
  - libopus-dev
  - libeigen3-dev
  - librtaudio-dev
