---
# vars file for wxwidgets

this_name: wxwidgets
this_version: '3.1.5'
name_version: '{{ this_name }}-{{ this_version }}'
required_system_packages:
  - build-essential
  - automake
  - libgtk-3-dev
  - freeglut3
  - freeglut3-dev
