---
# vars file for hamlib

this_name: hamlib
this_version: '4.4'
this_source_uri: 'https://github.com/Hamlib/Hamlib.git'

name_version: '{{ this_name }}-{{ this_version }}'
this_required_system_packages:
  - build-essential
  - libtool
  - automake
  - libfltk1.3-dev
  - libsamplerate0-dev
  - portaudio19-dev
  - libsndfile1-dev
  - libxft-dev
  - libxinerama-dev
  - libxcursor-dev
  - libpulse-dev
  - pavucontrol
  - swig
  - libusb-1.0-0-dev
  - libreadline-dev
  - libxml2-dev
  - libgd-dev
  - python3-dev
  - tcl-dev
  - lua5.3
  - liblua5.3-dev
this_conflicting_system_packages:
  - libhamlib*
